Fix typos
pylipp/financeager pull request #194
Opened 2024-01-03 17:09 UTC by kianmeng

Found via `codespell -S *.svg`

2024-01-03 17:21 UTC, pylipp commented on financeager/exceptions.py
> +"""Module defining expectations of the financeager application."""
Oh this should mean `exceptions` :sweat_smile:

2024-01-03 17:54 UTC, pylipp commented on test/test_pocket.py
> -                    "frequency": "yaerly",
This one's actually on purpose :)

2024-01-03 17:54 UTC, pylipp requested changes
thanks @kianmeng for the fixes!

2024-01-05 14:19 UTC, merged

2024-01-07 08:28 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: